Repository ucsb-cs156-s25/proj-frontiers-s25-07, pull requests merged in 2025-05, with the labels that each got.

#33 HY - Instructor POST and GET operation implementation
  src/main/java/edu/ucsb/cs156/frontiers/controllers/InstructorsController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/InstructorsControllerTests.java
Labels: 10, Merge Candidate-CI

#36 HY - Instructor DELETE operation implementation
  src/main/java/edu/ucsb/cs156/frontiers/controllers/InstructorsController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/InstructorsControllerTests.java
Labels: 10, Merge Candidate-CI

#35 Add PUT (update) for student roster controller plus tests
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/main/resources/db/migration/changes/006-RosterStudent-add-github-fields.json
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: 10, Merge Candidate-CI

#34 sz-Create Admin table (entity and repository)
  src/main/java/edu/ucsb/cs156/frontiers/entities/Admin.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/AdminRepository.java
  src/main/resources/db/migration/changes/008-create-Admins.json
Labels: 5, Merge Candidate-CI

#39 hz - add form for roster students
  frontend/src/fixtures/rosterStudentFixtures.js
  frontend/src/main/components/RosterStudent/RosterStudentForm.js
  frontend/src/stories/components/RosterStudent/RosterStudentForm.stories.js
  frontend/src/tests/components/RosterStudent/RosterStudentForm.test.js
Labels: 10, Merge Candidate-CI

#41 hz - add table for roster students
  frontend/src/main/components/RosterStudent/RosterStudentTable.js
  frontend/src/main/utils/rosterStudentUtils.js
  frontend/src/stories/components/RosterStudent/RosterStudentTable.stories.js
  frontend/src/tests/components/RosterStudent/RosterStudentTable.test.js
  frontend/src/tests/utils/rosterStudentUtils.test.js
Labels: 10, Merge Candidate-CI

#38 Add DELETE endpoint for student roster controller
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/main/java/edu/ucsb/cs156/frontiers/entities/Course.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: 10

#51 ad - Admin Post and Get Implementation (CRUD operations)
  src/main/java/edu/ucsb/cs156/frontiers/controllers/AdminsController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/AdminsControllerTests.java
Labels: 10, Merge Candidate-CI

#42 hz - Create RoleEmailForm component
  frontend/src/main/components/Users/RoleEmailForm.js
  frontend/src/stories/components/Users/RoleEmailForm.stories.js
  frontend/src/tests/components/Users/RoleEmailForm.test.js
Labels: 10, Merge Candidate-CI

#54 hz - fix error message for First Name field in RosterStudentForm
  frontend/src/main/components/RosterStudent/RosterStudentForm.js
Labels: 5, Merge Candidate-CI

#56 ad - ADMIN_EMAILS are added to the admins table at startup
  src/main/java/edu/ucsb/cs156/frontiers/startup/FrontiersApplicationRunner.java
  src/main/java/edu/ucsb/cs156/frontiers/startup/FrontiersStartup.java
  src/test/java/edu/ucsb/cs156/frontiers/startup/FrontiersApplicationRunnerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/startup/FrontiersStartupTests.java
Labels: 10, Merge Candidate-CI

#57 ad - Create frontend table component for listing emails
  frontend/src/main/components/Users/RoleEmailTable.js
  frontend/src/stories/components/Users/RoleEmailTable.stories.js
  frontend/src/tests/components/Users/RoleEmailTable.test.js
Labels: 10, Merge Candidate-CI
